name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # - name: Install dependencies
    #   run: npm install  # or your build commands
      
    # - name: Build project
    #   run: npm run build
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}  # Only if your key has passphrase
        script_strict: false  # Disables strict host key checking
        script: |
          # Setup SSH environment
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
          # Fix repository permissions
          sudo chown -R ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} /var/www/portfolio
          sudo chmod -R 755 /var/www/portfolio
          
          # Configure Git
          cd /var/www/portfolio
          git config --global --add safe.directory /var/www/portfolio
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Clean up any local changes
          git stash
          
          # Git operations
          git fetch --all
          git reset --hard origin/main
          git pull origin main
          
          # If you need to install dependencies
          # npm install --production
          
          # If you need to restart your application
          # pm2 restart all
