name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # - name: Install dependencies
    #   run: npm install  # or your build commands
      
    # - name: Build project
    #   run: npm run build
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}  # Must reference a secret, not direct IP
        username: ${{ secrets.EC2_USER }}  # Must reference a secret
        key: ${{ secrets.EC2_SSH_KEY }}
        # passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }} # If key has passphrase
        script: |
          # Setup SSH environment
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          
          # Create directory if it doesn't exist
          sudo mkdir -p /var/www/html/portfolio
          
          # Fix repository permissions
          sudo chown -R ${{ secrets.EC2_USER }}:${{ secrets.EC2_USER }} /var/www/html/portfolio
          sudo chmod -R 755 /var/www/html/portfolio
          
          # Initialize git repo if not already initialized
          cd /var/www/html/portfolio
          if [ ! -d .git ]; then
            git init
            git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git
          fi
          
          # Configure Git
          git config --global --add safe.directory /var/www/html/portfolio
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Git operations
          git fetch --all
          git reset --hard origin/main
          git pull origin main
