name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # - name: Install dependencies
    #   run: npm install  # or your build commands
      
    # - name: Build project
    #   run: npm run build
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ 13.203.208.66 }}
        username: ${{ ubuntu }}
        key: ${{ MIIEpQIBAAKCAQEAyV/5CYKF3w7B0bMqBXyp1GoULmElwxio0Vae7Vex5ofnorfCaTAawkg3xqUK9G+yFz9Mf8UN9SYj059aHAIaIT5WSQQUK3daHYK23mf2qth4W9IIxi+ycfMZn3cbl/ziAv/pIWlLtJbE5Gpbt+AjTScV5BtYbeOQHIG8ks3eV7dGwtNKM2Ti+d/nCx7PHFR7jM/GjHOIYZyiYequV+Tllvxuladj7Jewu1r7Ql9WHyt7MLiwGneyWh9DP7ABEZchGUxGiiTIOnxfGxIMCEXiq0VSn9XXT6P1+LwSSzEhdi3Q66b+/RtRTe9MZiDuKFZ7AAiyQmCpjf6I7gt06N5n8wIDAQABAoIBAQCSMHshfUDkatkn/BJAg3zi+NOHy/zXAlrkBidAFE7RFc6CITcgl8yFSFo9emlWhJPcLpbBlvOICdUud1u6Q4hmo9OOFEj0OSQRkmhhU0YORzIxLmwyPEQmVx491wEQOIR3OwMqvz83bdCoJdJJzYyzIPHSdEuhEvf2yfR0+sE0GU5YAiOxY5kwoWR9Vv0QnbyYWPWSqj81Xbj0pjauxrOCKJNgYp7GeS/CqfBl5HwhdDGAlulVDZCBdzHhx0RMyKzKZki5NxJr5PoRdaJ4gKtgiebxbbsBUPr+3WYJ+V/qGSWZx6ucP1mfnunoEQejBER1GzKmsl0ttzN7HQ5lueIhAoGBAO5On98r0+e8md40qeR5XTu8g+i/wjCpKZPg6PSBUQknwS1FiEOmNM98uqhaqXNM4yzprUeEL51HgxGPIBVcOjloMTOSgB02POjnKgob2LgVvngT4vDJpGoGhM0D76y7EuM1Ng0czcEr/IXeUN7PjABzWs2k+LNUNYr9AKbavDWRAoGBANhTZa5o7JBl3kK9zg6pr/xHhoL62u0AMl4WsAR2wU4sbzKxlUlYgOG1S4MZ9kLeP1uZ9xB42BLW6u3DY33PzHYIp9K37617LS77FO6JNGJI1Vs0O8vrtezwvq2AYYJ8poXkNrp3NNQR9DAUVjblJfnQI7z4VdhyvmQM5p3ZqLNDAoGBAMhLRy4BHVMZ/s13wA+rPgSWVtxKSAI0PCDxmXrgMecbBc9yMKyDRsHZ2NzljqS9S/eU1DJW1NpBn9UjUdkCMmHLxAbPrGRhEOLEYF4st4NJq1QrisPNByaiIf5av5iTh7V2JN7yhbFFsjImABy1nrtGOVy8utenAHW4XlLfZ+8xAoGBAL8TEso19VYqFGLBQiOjcEWWa9J/fyY9uT9wLLMUrfO9vc56GtG5McWrm/JF2UYBBteDLD5Jbxlc6g9vOQ7kn8VWKd4vB64lEajgsAFuAW4axRGVFogtP/j0QIgB0J8wOOokxM55Apma7iQVon1EdAGu/hIpC7Juz4qR9pVQrvj/AoGAQO92MasS7zYOouWlC7+P+my9Tw4T+Uo8adyUFFBsiCKwgwKEjOK0a+fZqNCPwJptCJyQn/Nfed8Q7ev2bQiqULRCzqQQqA3KuvlNW3gZsl+0qAcMO6CDhBgNCf7U0JQv1soYfIsTJjoeDDolomVGjxs3IP4TzEJXccl99VL5r6U= }}
        script: |
          cd /var/www/portfolio
          git pull origin main
          # npm install --production
          #pm2 restart all  # or your restart command
